version: '3.5'
services:
  app:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    command: [ "flask", "run", "--host", "0.0.0.0" ]
    depends_on:
      - database

  database:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: nguyen2442
      POSTGRES_PASSWORD: nguyen2442
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
