"""drop psw

Revision ID: caeb8ee21cf7
Revises: bc8578a64ece
Create Date: 2022-04-13 15:36:21.910632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caeb8ee21cf7'
down_revision = 'bc8578a64ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
