"""change flag to isAdmin

Revision ID: dcc4fd10bcb5
Revises: ee472e7d9604
Create Date: 2022-04-13 15:25:45.707298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc4fd10bcb5'
down_revision = 'ee472e7d9604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'flag')
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###
    op.execute("COMMIT")
