"""add psw again

Revision ID: 96efb08529ce
Revises: caeb8ee21cf7
Create Date: 2022-04-13 15:37:02.539986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96efb08529ce'
down_revision = 'caeb8ee21cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=500)))
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
    op.execute("COMMIT")
