"""add createdat updatedat

Revision ID: c097f9aa3cb3
Revises: 9a9aeb1f24ef
Create Date: 2022-04-14 15:51:50.235831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c097f9aa3cb3'
down_revision = '9a9aeb1f24ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('parts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pcs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pcs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pcs', 'updated_at')
    op.drop_column('pcs', 'created_at')
    op.drop_column('parts', 'updated_at')
    op.drop_column('parts', 'created_at')
    # ### end Alembic commands ###
