"""add d model component pc

Revision ID: 509366f6a75d
Revises: d76c6922835a
Create Date: 2022-04-08 18:01:20.034568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509366f6a75d'
down_revision = 'd76c6922835a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ),
    sa.PrimaryKeyConstraint('part_id', 'pc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components')
    # ### end Alembic commands ###
