"""adadd userId_created in pc model

Revision ID: 7c434f9ef435
Revises: b425e822c958
Create Date: 2022-04-12 11:35:46.679669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c434f9ef435'
down_revision = 'b425e822c958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pcs', sa.Column('userId_created', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pcs', 'users', ['userId_created'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pcs', type_='foreignkey')
    op.drop_column('pcs', 'userId_created')
    # ### end Alembic commands ###
