"""adadd isused field in part model

Revision ID: b425e822c958
Revises: 509366f6a75d
Create Date: 2022-04-12 09:57:03.019140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b425e822c958'
down_revision = '509366f6a75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('isUsed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'isUsed')
    # ### end Alembic commands ###
